//TODO Other Exercises, now its only for chest

export const EXERCISES = [
  {
    name: 'Supino reto com halter',
    level: 'intermediate_beginner',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino inclinado com halter',
    level: 'intermediate_beginner',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino declinado com halter',
    level: 'intermediate_beginner',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino maquina sentado',
    level: 'intermediate_beginner',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino maquina inclinado',
    level: 'beginner',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino maquina reto',
    level: 'beginner',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Peck deck',
    level: 'beginner',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Flexão de braços',
    level: 'beginner',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Cross over para parte inferior',
    level: 'beginner',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Cross over para parte medial',
    level: 'beginner',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino reto com barra',
    level: 'beginner',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Crucifixo reto com halteres',
    level: 'beginner',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Crucifixo fly máquina',
    level: 'beginner',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino reto com barra',
    level: 'ntermediate_beginner',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino inclinado com barra',
    level: 'intermediate_beginner',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino reto com halter',
    level: 'all',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino inclinado com halter',
    level: 'all',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino maquina sentado',
    level: 'all',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino maquina inclinado',
    level: 'intermediary',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino maquina reto',
    level: 'intermediary',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Crucifixo reto com halteres',
    level: 'intermediary',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Crucifixo inclinado com halteres',
    level: 'intermediary',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Crucifixo Reto cabo',
    level: 'intermediary',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Crucifixo inclinado cabo',
    level: 'intermediary',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Fly machine',
    level: 'intermediary',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Cross over para parte inferior',
    level: 'intermediary',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Cross over para parte medial',
    level: 'intermediary',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino reto com barra',
    level: 'advanced',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino inclinado com barra',
    level: 'advanced',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino declinado com barra',
    level: 'advanced',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino reto com barra neutra',
    level: 'advanced',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino inclinado com barra neutra',
    level: 'advanced',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino reto com halter',
    level: 'intermediate_advanced',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino inclinado com halter',
    level: 'intermediate_advanced',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino declinado com halter',
    level: 'intermediate_advanced',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino maquina sentado',
    level: 'intermediate_advanced',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino maquina inclinado',
    level: 'intermediate_advanced',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino maquina reto',
    level: 'intermediate_advanced',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Crucifixo reto com halteres',
    level: 'intermediate_advanced',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Crucifixo inclinado com halteres',
    level: 'intermediate_advanced',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Crucifixo declinado com halteres',
    level: 'all',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Crucifixo Reto cabo',
    level: 'advanced',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Crucifixo inclinado cabo',
    level: 'advanced',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Crucifixo declinado cabo',
    level: 'advanced',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Fly machine',
    level: 'advanced',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Pullover com halter',
    level: 'advanced',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Paralelas',
    level: 'advanced',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Cross over para parte inferior',
    level: 'all',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Cross over para parte medial',
    level: 'intermediate_advanced',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Cross over para parte superior',
    level: 'intermediate_advanced',
    muscle: 'chest',
    muscleId: 1,
  },

  {
    name: 'Supino reto com barra',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino inclinado com barra',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino declinado com barr',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino reto com barra neutra',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },

  {
    name: 'Supino inclinado com barra neutra',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino reto com halter',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino inclinado com halter',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino maquina sentado',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino maquina inclinado',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino maquina reto',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Crucifixo reto com halteres',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Crucifixo inclinado com halteres',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },

  {
    name: 'Crucifixo declinado com halteres',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },

  {
    name: 'Crucifixo Reto cabo',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Crucifixo inclinado cabo',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Crucifixo declinado cabo',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Fly machine',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Pullover com halter',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Paralelas',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Cross over para parte inferior',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Cross over para parte medial',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Cross over para parte superior',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Pulldown com corda',
    level: 'intermediate_beginner',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulldown barra reta cabo',
    level: 'intermediate_beginner',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada com corda no Cabo',
    level: 'intermediate_beginner',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada baixa Neutra',
    level: 'intermediate_beginner',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada baixa Supinada',
    level: 'intermediate_beginner',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada baixa Pronada',
    level: 'intermediate_beginner',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada Maquina convergente Neutra',
    level: 'beginner',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada Maquina convergente Supinada',
    level: 'beginner',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada Maquina convergente Pronada',
    level: 'beginner',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulley frente fechado',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulley frente supinado',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulldown com corda',
    level: 'intermediary',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulldown barra reta cabo',
    level: 'intermediary',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada com corda no Cabo',
    level: 'intermediary',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada com corda no Cabo',
    level: 'intermediary',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada baixa Neutra',
    level: 'intermediary',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada baixa Supinada',
    level: 'intermediary',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada baixa Pronada',
    level: 'intermediary',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada Maquina convergente Neutra',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada Maquina convergente Supinada',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada Maquina convergente Pronada',
    level: 'intermediary',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulley frente fechado',
    level: 'intermediary',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulley frente supinado',
    level: 'intermediary',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Levantamento terra 1/2 movimento',
    level: 'advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Levantamento terra completo',
    level: 'advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulldown com corda',
    level: 'advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulldown barra reta cabo',
    level: 'advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada banco livre com halteres Supinada',
    level: 'advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada banco livre com halteres Pronada',
    level: 'advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada unilateral com Halteres',
    level: 'advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada baixa Neutra',
    level: 'advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada baixa Supinada',
    level: 'advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada baixa Pronada',
    level: 'advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada Maquina convergente Neutra',
    level: 'advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada Maquina convergente Supinada',
    level: 'advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada Maquina convergente Pronada',
    level: 'advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada Cavalo',
    level: 'advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada curvada Supinada',
    level: 'advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada curvada Pronada',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Puxador convergente Neutro',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Puxador convergente Supinado',
    level: 'advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Puxador convergente Pronado',
    level: 'advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulley Costas Pronado',
    level: 'advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulley Costas Neutro',
    level: 'advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulley Costas fechado',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulley Costas supinado',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulley Costas pronado',
    level: 'intermediate_advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Barra fixa neutra',
    level: 'intermediate_advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Barra fixa supinada',
    level: 'intermediate_advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Barra fixa pronada',
    level: 'intermediate_advanced',
    muscle: 'back',
    muscleId: 2,
  },

  {
    name: 'Levantamento terra 1/2 movimento"',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Levantamento terra completo',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulldown com corda',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada banco livre com halteres Supinada',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada banco livre com halteres Pronada',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada unilateral com Halteres',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada baixa Neutra',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada baixa Supinada',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada baixa Pronada',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada Maquina convergente Neutra',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada Maquina convergente Supinada',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada Maquina convergente Pronada',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada Cavalo',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada curvada Supinada',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada curvada Pronada',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Puxador convergente Neutro',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Puxador convergente Supinado',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Puxador convergente Pronado',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulley Costas Pronado',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulley Costas Neutro',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulley frente fechado',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulley frente supinado',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulley frente pronado',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Barra fixa neutra',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Barra fixa supinada',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Barra fixa pronada',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },

  {
    name: 'Elevação frontal com halter pronada',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação frontal com halter neutra',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Desenvolvimento Maquina pegada neutra',
    level: 'beginner',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação lateral sentado com halteres',
    level: 'beginner',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação lateral em pé com halteres',
    level: 'beginner',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Desenvolvimento máquina convergente',
    level: 'beginner',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação frontal com halter pronada',
    level: 'intermediary',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação frontal com halter neutra',
    level: 'intermediary',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Desenvolvimento barra guiada frente',
    level: 'intermediary',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Desenvolvimento Maquina pegada neutra',
    level: 'intermediary',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Remada alta cabo pegada aberta',
    level: 'intermediary',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Remada alta barra pegada aberta',
    level: 'intermediary',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação lateral sentado com halteres',
    level: 'intermediary',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação lateral em pé com halteres',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação unilateral com halteres em pé',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Desenvolvimento com Halteres',
    level: 'intermediary',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Desenvolvimento máquina convergente',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Maquina Fly inverso',
    level: 'intermediary',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Remada alta com barra reta',
    level: 'intermediary',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Encolhimento halteres lateral',
    level: 'intermediary',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Encolhimento barra pela frente',
    level: 'intermediary',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Desenvolvimento máquina convergente',
    level: 'intermediate_advanced',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Desenvolvimento com Halteres',
    level: 'intermediate_advanced',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação Inilteral com halter sentado banco inclinado',
    level: 'intermediate_advanced',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação unilateral com halteres em pé',
    level: 'intermediate_advanced',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação unilateral cabo por trás',
    level: 'intermediate_advanced',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação unilateral cabo pela frente',
    level: 'intermediate_advanced',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação lateral com anilhas',
    level: 'intermediate_advanced',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação lateral em pé cabo',
    level: 'intermediate_advanced',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação lateral em pé com halteres',
    level: 'intermediate_advanced',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação lateral sentado with halteres',
    level: 'intermediate_advanced',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Remada alta barra pegada aberta',
    level: 'intermediate_advanced',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Remada alta halter pegada aberta',
    level: 'intermediate_advanced',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Remada alta cabo pegada aberta',
    level: 'advanced',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Desenvolvimento com polias cross over',
    level: 'advanced',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Desenvolvimento frontal barra livre',
    level: 'advanced',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Desenvolvimento Arnold Press',
    level: 'advanced',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Desenvolvimento com halteres Neutro',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação frontal com halter neutra',
    level: 'advanced',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação frontal com halter supinada',
    level: 'advanced',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Encolhimento barra por tras',
    level: 'advanced',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Encolhimento barra pela frente',
    level: 'advanced',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Encolhimento halteres lateral',
    level: 'advanced',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Encolhimento halteres frontal',
    level: 'advanced',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Remada alta com corda polia alta',
    level: 'advanced',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Remada alta com barra reta',
    level: 'advanced',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'crucifixo inverso unilateral cabo',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'crucifixo inverso cruzado cabo',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Crucifixo inverso sentado com halteres',
    level: 'advanced',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Crucifixo inverso com halteres com apoio no banco',
    level: 'advanced',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Maquina Fly inverso',
    level: 'advanced',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação frontal com halter pronada',
    level: 'advanced',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Desenvolvimento máquina convergente',
    level: 'pro',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Desenvolvimento com Halteres',
    level: 'pro',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação Inilteral com halter sentado banco inclinado',
    level: 'pro',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação unilateral com halteres em pé',
    level: 'pro',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação unilateral cabo por trás',
    level: 'pro',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação unilateral cabo pela frente',
    level: 'pro',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação lateral com anilhas',
    level: 'pro',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação lateral em pé cabo',
    level: 'pro',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação lateral em pé com halteres',
    level: 'pro',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação lateral sentado with halteres',
    level: 'pro',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Remada alta barra pegada aberta',
    level: 'pro',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Remada alta halter pegada aberta',
    level: 'pro',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Remada alta cabo pegada aberta',
    level: 'pro',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Desenvolvimento com polias cross over',
    level: 'pro',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Desenvolvimento frontal barra livre',
    level: 'pro',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Desenvolvimento Arnold Press',
    level: 'pro',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Desenvolvimento com halteres Neutro',
    level: 'pro',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação frontal com halter neutra',
    level: 'pro',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação frontal com halter supinada',
    level: 'pro',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Encolhimento barra por tras',
    level: 'pro',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Encolhimento barra pela frente',
    level: 'pro',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Encolhimento halteres lateral',
    level: 'pro',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Encolhimento halteres frontal',
    level: 'pro',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Remada alta com corda polia alta',
    level: 'pro',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Remada alta com barra reta',
    level: 'pro',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'crucifixo inverso unilateral cabo',
    level: 'pro',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'crucifixo inverso cruzado cabo',
    level: 'pro',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Crucifixo inverso sentado with halteres',
    level: 'pro',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Crucifixo inverso com halteres com apoio no banco',
    level: 'pro',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Maquina Fly inverso',
    level: 'pro',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação frontal com halter pronada',
    level: 'pro',
    muscle: 'shoulders',
    muscleId: 3,
  },

  {
    name: 'Cadeira extensora',
    level: 'all',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Cadeira extensora unilateral',
    level: 'all',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Leg press 45 pés afastados',
    level: 'beginner',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Agachamento livre pés afastados',
    level: 'beginner',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Agachamento com halter pés afastados',
    level: 'beginner',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Leg press horizontal pés afastados',
    level: 'beginner',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Adutor/abdutor Maquina',
    level: 'beginner',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Cadeira extensora',
    level: 'intermediary',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Cadeira extensora unilateral',
    level: 'intermediary',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Leg press 45 pés afastados',
    level: 'intermediary',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Agachamento livre pés afastados',
    level: 'intermediary',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Agachamento com halter pés afastados',
    level: 'intermediary',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Leg press horizontal pés afastados',
    level: 'intermediary',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Adutor/abdutor Maquina',
    level: 'all',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Agachamento com halter Sumô',
    level: 'all',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Agachamento com halter pés juntos',
    level: 'all',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Leg press horizontal pés juntos',
    level: 'intermediary',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Leg press horizontal sumô',
    level: 'intermediary',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Leg press horizontal unilateral',
    level: 'intermediary',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Cadeira extensora',
    level: 'advanced',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Cadeira extensora unilateral',
    level: 'advanced',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Leg press 45 pés afastados',
    level: 'advanced',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Agachamento livre pés afastados',
    level: 'advanced',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Agachamento com halter pés afastados',
    level: 'advanced',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Adutor/abdutor Maquina',
    level: 'advanced',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Agachamento com halter Sumô',
    level: 'advanced',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Agachamento com halter pés juntos',
    level: 'all',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Leg press horizontal pés juntos',
    level: 'all',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Leg press horizontal sumô',
    level: 'all',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Leg press horizontal unilateral',
    level: 'advanced',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Agachamento Sumô',
    level: 'advanced',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Agachamento livre pés juntos',
    level: 'advanced',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Leg press unilateral',
    level: 'intermediate_advanced',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Leg press 45 sumô',
    level: 'intermediate_advanced',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Leg press 45 pés juntos',
    level: 'all',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Passada com halteres',
    level: 'intermediate_advanced',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Passada com barra',
    level: 'intermediate_advanced',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Hack machine pés afastados',
    level: 'advanced',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Hack machine pés juntos',
    level: 'advanced',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Agachamento unilateral',
    level: 'advanced',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Cadeira extensora',
    level: 'pro',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Cadeira extensora unilateral',
    level: 'pro',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Leg press 45 pés afastados',
    level: 'pro',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Agachamento livre pés afastados',
    level: 'pro',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Agachamento com halter pés afastados',
    level: 'pro',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Adutor/abdutor Maquina',
    level: 'pro',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Agachamento com halter Sumô',
    level: 'pro',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Agachamento com halter pés juntos',
    level: 'pro',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Leg press horizontal pés juntos',
    level: 'pro',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Leg press horizontal sumô',
    level: 'pro',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Leg press horizontal unilateral',
    level: 'pro',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Agachamento Sumô',
    level: 'pro',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Agachamento livre pés juntos',
    level: 'pro',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Leg press unilateral',
    level: 'pro',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Leg press 45 sumô',
    level: 'pro',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Leg press 45 pés juntos',
    level: 'pro',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Passada com halteres',
    level: 'pro',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Passada com barra',
    level: 'pro',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Hack machine pés afastados',
    level: 'pro',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Hack machine pés juntos',
    level: 'pro',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Agachamento unilateral',
    level: 'pro',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Syssi squat',
    level: 'pro',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Hack machine unilteral',
    level: 'pro',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Hack machine invertido',
    level: 'pro',
    muscle: 'quads',
    muscleId: 4,
  },

  {
    name: 'Mesa Flexora pés juntos',
    level: 'all',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Mesa Flexora pés afastados',
    level: 'all',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Cadeira flexora pés juntos',
    level: 'all',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Cadeira flexora pés afastados',
    level: 'beginner',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Gluteo com caneleira joelhos flexionados',
    level: 'beginner',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Gluteos com caneleira joelhos Estendidos',
    level: 'beginner',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Mesa Flexora pés juntos',
    level: 'intermediary',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Mesa Flexora pés afastados',
    level: 'intermediary',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Cadeira flexora pés juntos',
    level: 'all',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Cadeira flexora pés afastados',
    level: 'all',
    muscle: 'femural',
    muscleId: 5,
  },
  { name: 'Stiff com halteres', level: 'all', muscle: 'femural', muscleId: 5 },
  {
    name: 'Stiff com barra',
    level: 'intermediary',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Stiff com barra guiada',
    level: 'intermediary',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Stiff no cabo',
    level: 'intermediary',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Abdutor maquina',
    level: 'intermediary',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Gluteo no cabo joelhos flexionados',
    level: 'intermediary',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Gluteo no cabo joelhos estendidos',
    level: 'intermediary',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Gluteo maquina',
    level: 'intermediary',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Gluteo com caneleira joelhos flexionados',
    level: 'intermediary',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Gluteos com caneleira joelhos Estendidos',
    level: 'intermediary',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Mesa Flexora unilateral',
    level: 'advanced',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Cadeira flexora pés afastados',
    level: 'advanced',
    muscle: 'femural',
    muscleId: 5,
  },
  { name: 'Flexora em pé', level: 'advanced', muscle: 'femural', muscleId: 5 },
  {
    name: 'Hiperextensão lombar com enfase em gluteos',
    level: 'advanced',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Mesa Flexora pés juntos',
    level: 'all',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Mesa Flexora pés afastados',
    level: 'all',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Cadeira flexora pés juntos',
    level: 'all',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Cadeira flexora pés afastados',
    level: 'advanced',
    muscle: 'femural',
    muscleId: 5,
  },
  { name: 'Stiff com halteres', level: 'all', muscle: 'femural', muscleId: 5 },
  { name: 'Stiff com barra', level: 'all', muscle: 'femural', muscleId: 5 },
  {
    name: 'Stiff com barra guiada',
    level: 'all',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Stiff no cabo',
    level: 'intermediate_advanced',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Abdutor maquina',
    level: 'intermediate_advanced',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Gluteo no cabo joelhos flexionados',
    level: 'advanced',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Gluteo no cabo joelhos estendidos',
    level: 'advanced',
    muscle: 'femural',
    muscleId: 5,
  },
  { name: 'Gluteo maquina', level: 'advanced', muscle: 'femural', muscleId: 5 },
  {
    name: 'Mesa Flexora pés juntos',
    level: 'pro',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Mesa Flexora pés afastados',
    level: 'pro',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Cadeira flexora pés juntos',
    level: 'pro',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Cadeira flexora pés afastados',
    level: 'pro',
    muscle: 'femural',
    muscleId: 5,
  },
  { name: 'Stiff com halteres', level: 'pro', muscle: 'femural', muscleId: 5 },
  { name: 'Stiff com barra', level: 'pro', muscle: 'femural', muscleId: 5 },
  {
    name: 'Stiff com barra guiada',
    level: 'pro',
    muscle: 'femural',
    muscleId: 5,
  },
  { name: 'Stiff no cabo', level: 'pro', muscle: 'femural', muscleId: 5 },
  { name: 'Abdutor maquina', level: 'pro', muscle: 'femural', muscleId: 5 },
  {
    name: 'Gluteo no cabo joelhos flexionados',
    level: 'pro',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Gluteo no cabo joelhos estendidos',
    level: 'pro',
    muscle: 'femural',
    muscleId: 5,
  },
  { name: 'Gluteo maquina', level: 'pro', muscle: 'femural', muscleId: 5 },

  { name: "rosca inversa no cabo", level: "intermediary", muscle: "biceps", muscleId: 6 },
  { name: "rosca inversa barra reta", level: "advanced", muscle: "biceps", muscleId: 6 },
  { name: "rosca inversa barra w", level: "advanced", muscle: "biceps", muscleId: 6 },
  { name: "rosca inversa no cabo", level: "advanced", muscle: "biceps", muscleId: 6 },
  { name: "rosca punho barra reta", level: "advanced", muscle: "biceps", muscleId: 6 },
  { name: "rosca punho cabo", level: "intermediate_advanced", muscle: "biceps", muscleId: 6 },
  { name: "rosca inversa barra reta", level: "pro", muscle: "biceps", muscleId: 6 },
  { name: "rosca inversa barra w", level: "pro", muscle: "biceps", muscleId: 6 },
  { name: "rosca inversa maquina scoth", level: "pro", muscle: "biceps", muscleId: 6 },
  { name: "rosca inversa halteres", level: "pro", muscle: "biceps", muscleId: 6 },
  { name: "rosca punho barra reta", level: "pro", muscle: "biceps", muscleId: 6 },
  { name: "rosca punho cabo", level: "pro", muscle: "biceps", muscleId: 6 },
  { name: "rosca punho com halteres", level: "pro", muscle: "biceps", muscleId: 6 },

  { name: "triceps polia barra reta", level: "all", muscle: "triceps", muscleId: 7 },
  { name: "triceps polia corda", level: "beginner", muscle: "triceps", muscleId: 7 },
  { name: "triceps maquina pegada neutra", level: "beginner", muscle: "triceps", muscleId: 7 },
  { name: "triceps polia barra reta", level: "intermediary", muscle: "triceps", muscleId: 7 },
  { name: "triceps polia corda", level: "intermediary", muscle: "triceps", muscleId: 7 },
  { name: "Triceps testa com barra reta", level: "intermediary", muscle: "triceps", muscleId: 7 },
  { name: "triceps testa com barra w", level: "intermediary", muscle: "triceps", muscleId: 7 },
  { name: "triceps frances com halter", level: "intermediary", muscle: "triceps", muscleId: 7 },
  { name: "triceps frances unilateral", level: "intermediary", muscle: "triceps", muscleId: 7 },
  { name: "triceps maquina pegada neutra", level: "intermediary", muscle: "triceps", muscleId: 7 },
  { name: "triceps polia barra reta", level: "intermediate_advanced", muscle: "triceps", muscleId: 7 },
  { name: "triceps polia barra w", level: "intermediate_advanced", muscle: "triceps", muscleId: 7 },
  { name: "triceps maquina pegada neutra", level: "intermediate_advanced", muscle: "triceps", muscleId: 7 },
  { name: "triceps banco", level: "intermediate_advanced", muscle: "triceps", muscleId: 7 },
  { name: "Triceps paralelas", level: "intermediate_advanced", muscle: "triceps", muscleId: 7 },
  { name: "triceps frances unilateral", level: "intermediate_advanced", muscle: "triceps", muscleId: 7 },
  { name: "triceps frances com halter", level: "advanced", muscle: "triceps", muscleId: 7 },
  { name: "triceps frances com corda", level: "advanced", muscle: "triceps", muscleId: 7 },
  { name: "triceps polia corda", level: "advanced", muscle: "triceps", muscleId: 7 },
  { name: "triceps polia inverso", level: "advanced", muscle: "triceps", muscleId: 7 },
  { name: "Triceps testa com barra reta", level: "advanced", muscle: "triceps", muscleId: 7 },
  { name: "triceps frances com barra w", level: "advanced", muscle: "triceps", muscleId: 7 },
  { name: "triceps testa com barra w", level: "advanced", muscle: "triceps", muscleId: 7 },
  { name: "triceps frances com barra reta", level: "advanced", muscle: "triceps", muscleId: 7 },
  { name: "triceps testa com halteres", level: "pro", muscle: "triceps", muscleId: 7 },
  { name: "triceps testa com barra neutra", level: "pro", muscle: "triceps", muscleId: 7 },
  { name: "triceps testa com barra w", level: "pro", muscle: "triceps", muscleId: 7 },
  { name: "Triceps testa com barra reta", level: "pro", muscle: "triceps", muscleId: 7 },
  { name: "triceps polia com triangulo", level: "pro", muscle: "triceps", muscleId: 7 },
  { name: "triceps polia inverso unilateral", level: "pro", muscle: "triceps", muscleId: 7 },
  { name: "triceps polia inverso", level: "pro", muscle: "triceps", muscleId: 7 },
  { name: "triceps polia corda", level: "pro", muscle: "triceps", muscleId: 7 },
  { name: "triceps polia barra w", level: "pro", muscle: "triceps", muscleId: 7 },
  { name: "triceps polia barra reta", level: "pro", muscle: "triceps", muscleId: 7 },
  { name: "triceps frances com barra reta", level: "pro", muscle: "triceps", muscleId: 7 },
  { name: "triceps frances com barra w", level: "pro", muscle: "triceps", muscleId: 7 },
  { name: "triceps frances com corda", level: "pro", muscle: "triceps", muscleId: 7 },
  { name: "triceps frances com halter", level: "pro", muscle: "triceps", muscleId: 7 },
  { name: "triceps frances unilateral", level: "pro", muscle: "triceps", muscleId: 7 },
  { name: "Triceps paralelas", level: "pro", muscle: "triceps", muscleId: 7 },
  { name: "triceps banco", level: "pro", muscle: "triceps", muscleId: 7 },
  { name: "supinação com pegada fechada", level: "pro", muscle: "triceps", muscleId: 7 },
  { name: "triceps maquina pegada neutra", level: "pro", muscle: "triceps", muscleId: 7 },


  { name: "abdominal solo com peso", level: "all", muscle: "abdominal", muscleId: 8 },
  { name: "abdominal solo sem peso", level: "beginner", muscle: "abdominal", muscleId: 8 },
  { name: "abdominal solo com bola", level: "beginner", muscle: "abdominal", muscleId: 8 },
  { name: "obliquos solo", level: "beginner", muscle: "abdominal", muscleId: 8 },
  { name: "obliquos cruzado solo", level: "beginner", muscle: "abdominal", muscleId: 8 },
  { name: "infra abdominal no solo", level: "beginner", muscle: "abdominal", muscleId: 8 },
  { name: "abdominal solo com peso", level: "intermediary", muscle: "abdominal", muscleId: 8 },
  { name: "abdominal solo sem peso", level: "intermediary", muscle: "abdominal", muscleId: 8 },
  { name: "abdominal solo com bola", level: "intermediary", muscle: "abdominal", muscleId: 8 },
  { name: "obliquos solo", level: "intermediary", muscle: "abdominal", muscleId: 8 },
  { name: "obliquos cruzado solo", level: "intermediary", muscle: "abdominal", muscleId: 8 },
  { name: "obliquos cabo", level: "intermediary", muscle: "abdominal", muscleId: 8 },
  { name: "infra abdominal no banco", level: "intermediary", muscle: "abdominal", muscleId: 8 },
  { name: "infra com halter preso nos pés", level: "intermediate_advanced", muscle: "abdominal", muscleId: 8 },
  { name: "infra abdominal com caneleira", level: "intermediate_advanced", muscle: "abdominal", muscleId: 8 },
  { name: "infraabdominal com bola", level: "intermediate_advanced", muscle: "abdominal", muscleId: 8 },
  { name: "infra abdominal na prancha", level: "advanced", muscle: "abdominal", muscleId: 8 },
  { name: "obliquos cabo", level: "advanced", muscle: "abdominal", muscleId: 8 },
  { name: "abdominal crunch no cross", level: "advanced", muscle: "abdominal", muscleId: 8 },
  { name: "abdominal na prancha", level: "advanced", muscle: "abdominal", muscleId: 8 },
  { name: "infraabdominal na barra", level: "pro", muscle: "abdominal", muscleId: 8 },
  { name: "infra abdominal na prancha", level: "pro", muscle: "abdominal", muscleId: 8 },
  { name: "canivete cruzado solo", level: "pro", muscle: "abdominal", muscleId: 8 },
  { name: "obliquos cabo", level: "pro", muscle: "abdominal", muscleId: 8 },
  { name: "abdominal crunch no cross", level: "pro", muscle: "abdominal", muscleId: 8 },
  { name: "abdominal na prancha", level: "pro", muscle: "abdominal", muscleId: 8 },
  { name: "infraabdominal com bola", level: "pro", muscle: "abdominal", muscleId: 8 },
  { name: "infra abdominal com caneleira", level: "pro", muscle: "abdominal", muscleId: 8 },
  { name: "infra com halter preso nos pés", level: "pro", muscle: "abdominal", muscleId: 8 },

  { name: "panturrilha em pé maquina pés retos", level: "all", muscle: "panturrilha", muscleId: 9 },
  { name: "panturrilha sentado pés retos", level: "beginner", muscle: "panturrilha", muscleId: 9 },
  { name: "panturrilhas em pé unilateral", level: "beginner", muscle: "panturrilha", muscleId: 9 },
  { name: "panturrilha em pé maquina pés retos", level: "intermediary", muscle: "panturrilha", muscleId: 9 },
  { name: "panturrilha sentado pés retos", level: "intermediary", muscle: "panturrilha", muscleId: 9 },
  { name: "panturrilhas em pé unilateral", level: "intermediary", muscle: "panturrilha", muscleId: 9 },
  { name: "panturrilha em pé maquina pés retos", level: "advanced", muscle: "panturrilha", muscleId: 9 },
  { name: "panturrilha sentado pés retos", level: "advanced", muscle: "panturrilha", muscleId: 9 },
  { name: "panturrilhas em pé unilateral", level: "advanced", muscle: "panturrilha", muscleId: 9 },
  { name: "Panturrilha em pé maquina pés abduzidos", level: "advanced", muscle: "panturrilha", muscleId: 9 },
  { name: "panturrilhas leg press unilateral", level: "advanced", muscle: "panturrilha", muscleId: 9 },
  { name: "panturrilhas sentado unilteral", level: "advanced", muscle: "panturrilha", muscleId: 9 },
  { name: "panturrilhas leg press pés aduzidos", level: "advanced", muscle: "panturrilha", muscleId: 9 },
  { name: "panturrilhas leg press pés abduzidos", level: "advanced", muscle: "panturrilha", muscleId: 9 },
  { name: "panturrilha leg press pés retos", level: "intermediate_advanced", muscle: "panturrilha", muscleId: 9 },
  { name: "panturrilha em pé maquina pés aduzidos", level: "intermediate_advanced", muscle: "panturrilha", muscleId: 9 },
  { name: "panturrilha sentado pés aduzidos", level: "intermediate_advanced", muscle: "panturrilha", muscleId: 9 },
  { name: "panturrilha sentado pés abduzidos", level: "advanced", muscle: "panturrilha", muscleId: 9 },
  { name: "panturrilha em pé maquina pés retos", level: "pro", muscle: "panturrilha", muscleId: 9 },
  { name: "panturrilha sentado pés retos", level: "pro", muscle: "panturrilha", muscleId: 9 },
  { name: "panturrilhas em pé unilateral", level: "pro", muscle: "panturrilha", muscleId: 9 },
  { name: "Panturrilha em pé maquina pés abduzidos", level: "pro", muscle: "panturrilha", muscleId: 9 },
  { name: "panturrilhas leg press unilateral", level: "pro", muscle: "panturrilha", muscleId: 9 },
  { name: "panturrilhas sentado unilteral", level: "pro", muscle: "panturrilha", muscleId: 9 },
  { name: "panturrilhas leg press pés aduzidos", level: "pro", muscle: "panturrilha", muscleId: 9 },
  { name: "panturrilhas leg press pés abduzidos", level: "pro", muscle: "panturrilha", muscleId: 9 },
  { name: "panturrilha leg press pés retos", level: "pro", muscle: "panturrilha", muscleId: 9 },
  { name: "panturrilha em pé maquina pés aduzidos", level: "pro", muscle: "panturrilha", muscleId: 9 },
  { name: "panturrilha sentado pés aduzidos", level: "pro", muscle: "panturrilha", muscleId: 9 },
  { name: "panturrilha sentado pés abduzidos", level: "pro", muscle: "panturrilha", muscleId: 9 }
];
