export const EXERCISES = [
  {
    name: 'Supino declinado com halter',
    level: 'all',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino maquina reto',
    level: 'all',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Peck deck',
    level: 'all',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Flexão de braços',
    level: 'all',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Cross over para parte inferior',
    level: 'all',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Cross over para parte medial',
    level: 'all',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino reto com barra',
    level: 'all',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Crucifixo fly máquina',
    level: 'all',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino inclinado com barra',
    level: 'all',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino reto com halter',
    level: 'all',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino inclinado com halter',
    level: 'all',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino maquina sentado',
    level: 'all',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Crucifixo Reto cabo',
    level: 'all',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Crucifixo inclinado com halteres',
    level: 'all',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Crucifixo declinado com halteres',
    level: 'all',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Crucifixo inclinado cabo',
    level: 'all',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Crucifixo declinado cabo',
    level: 'all',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Fly machine',
    level: 'all',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Paralelas',
    level: 'all',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Pullover com halter',
    level: 'all',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Cross over para parte superior',
    level: 'all',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino declinado com barra',
    level: 'all',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino inclinado com barra neutra',
    level: 'all',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino maquina inclinado',
    level: 'all',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Crucifixo reto com halteres',
    level: 'all',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Pulldown com corda',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulldown barra reta cabo',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada com corda no Cabo',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada baixa Neutra',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada baixa Supinada',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada baixa alternada',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada Maquina convergente Neutra',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada Maquina convergente Supinada',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada Maquina convergente alternada',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulley frente fechado',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulley frente supinado',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Levantamento terra 1/2 movimento',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Levantamento terra completo',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada banco livre com halteres Supinada',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada banco livre com halteres alternada',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada unilateral com Halteres',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada curvada Supinada',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada curvada alternada',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Puxador convergente Neutro',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Puxador convergente Supinado',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Puxador convergente allnado',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulley Costas allnado',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulley Costas Neutro',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulley frente supinado',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulley frente allnado',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Barra fixa neutra',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Barra fixa supinada',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Barra fixa alternada',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Elevação frontal com halter alternada',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação frontal com halter neutra',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Desenvolvimento Maquina pegada neutra',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação lateral sentado com halteres',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Desenvolvimento máquina convergente',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Desenvolvimento barra guiada frente',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação unilateral com halteres em pé',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Desenvolvimento com Halteres',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Maquina Fly inverso',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Remada alta com barra reta',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Encolhimento halteres lateral',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Encolhimento barra pela frente',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação Inilteral com halter sentado banco inclinado',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação unilateral cabo por trás',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação unilateral cabo pela frente',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação lateral com anilhas',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação lateral em pé cabo',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação lateral sentado with halteres',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Remada alta cabo pegada aberta',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Desenvolvimento com halteres Neutro',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação frontal com halter neutra',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação frontal com halter supinada',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Encolhimento barra por tras',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Encolhimento halteres lateral',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Encolhimento halteres frontal',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Remada alta com corda polia alta',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Remada alta com barra reta',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'crucifixo inverso unilateral cabo',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'crucifixo inverso cruzado cabo',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Crucifixo inverso sentado com halteres',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Crucifixo inverso com halteres com apoio no banco',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação frontal com halter alternada',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação Inilteral com halter sentado banco inclinado',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação unilateral com halteres em pé',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação unilateral cabo por trás',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação unilateral cabo pela frente',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação lateral com anilhas',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação lateral em pé cabo',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação lateral em pé com halteres',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação lateral sentado with halteres',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Remada alta barra pegada aberta',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Remada alta halter pegada aberta',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Desenvolvimento com polias cross over',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Desenvolvimento frontal barra livre',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Desenvolvimento Arnold Press',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Desenvolvimento com halteres Neutro',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação frontal com halter neutra',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Elevação frontal com halter supinada',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Encolhimento barra por tras',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Encolhimento barra pela frente',
    level: 'all',
    muscle: 'shoulders',
    muscleId: 3,
  },
  {
    name: 'Cadeira extensora',
    level: 'all',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Cadeira extensora unilateral',
    level: 'all',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Leg press 45 pés afastados',
    level: 'all',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Adutor/abdutor Maquina',
    level: 'all',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Agachamento livre pés afastados',
    level: 'all',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Agachamento com halter pés afastados',
    level: 'all',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Leg press horizontal pés afastados',
    level: 'all',
    muscle: 'quads',
    muscleId: 4,
  },

  {
    name: 'Agachamento com halter Sumô',
    level: 'all',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Agachamento com halter pés juntos',
    level: 'all',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Leg press horizontal sumô',
    level: 'all',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Leg press horizontal unilateral',
    level: 'all',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Agachamento Sumô',
    level: 'all',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Agachamento livre pés juntos',
    level: 'all',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Leg press unilateral',
    level: 'all',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Leg press 45 sumô',
    level: 'all',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Leg press 45 pés juntos',
    level: 'all',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Passada com halteres',
    level: 'all',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Passada com barra',
    level: 'all',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Hack machine pés afastados',
    level: 'all',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Hack machine pés juntos',
    level: 'all',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Agachamento unilateral',
    level: 'all',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Mesa Flexora pés juntos',
    level: 'all',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Mesa Flexora pés afastados',
    level: 'all',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Cadeira flexora pés juntos',
    level: 'all',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Cadeira flexora pés afastados',
    level: 'all',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Gluteo com caneleira joelhos flexionados',
    level: 'all',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Gluteos com caneleira joelhos Estendidos',
    level: 'all',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Stiff com barra',
    level: 'all',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Stiff com barra guiada',
    level: 'all',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Stiff no cabo',
    level: 'all',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Abdutor maquina',
    level: 'all',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Gluteo no cabo joelhos flexionados',
    level: 'all',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Gluteo no cabo joelhos estendidos',
    level: 'all',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Gluteo maquina',
    level: 'all',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Syssi squat',
    level: 'all',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Hack machine unilteral',
    level: 'all',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Hack machine invertido',
    level: 'all',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Stiff com halteres',
    level: 'all',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Abdutor maquina',
    level: 'all',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Gluteo no cabo joelhos flexionados',
    level: 'all',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Gluteo no cabo joelhos estendidos',
    level: 'all',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Gluteo maquina',
    level: 'all',
    muscle: 'femural',
    muscleId: 5,
  },
  {
    name: 'Syssi squat',
    level: 'all',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Hack machine unilteral',
    level: 'all',
    muscle: 'quads',
    muscleId: 4,
  },
  {
    name: 'Hack machine invertido',
    level: 'all',
    muscle: 'quads',
    muscleId: 4,
  },

  {
    name: 'rosca inversa no cabo',
    level: 'all',
    muscle: 'biceps',
    muscleId: 6,
  },
  {
    name: 'rosca inversa barra reta',
    level: 'all',
    muscle: 'biceps',
    muscleId: 6,
  },
  {
    name: 'rosca inversa barra w',
    level: 'all',
    muscle: 'biceps',
    muscleId: 6,
  },
  {
    name: 'rosca punho barra reta',
    level: 'all',
    muscle: 'biceps',
    muscleId: 6,
  },
  {
    name: 'rosca punho cabo',
    level: 'all',
    muscle: 'biceps',
    muscleId: 6,
  },
  {
    name: 'rosca inversa maquina scoth',
    level: 'all',
    muscle: 'biceps',
    muscleId: 6,
  },
  {
    name: 'rosca inversa halteres',
    level: 'all',
    muscle: 'biceps',
    muscleId: 6,
  },
  {
    name: 'rosca punho com halteres',
    level: 'all',
    muscle: 'biceps',
    muscleId: 6,
  },

  {
    name: 'triceps polia barra reta',
    level: 'all',
    muscle: 'triceps',
    muscleId: 7,
  },
  {
    name: 'triceps polia corda',
    level: 'all',
    muscle: 'triceps',
    muscleId: 7,
  },
  {
    name: 'triceps maquina pegada neutra',
    level: 'all',
    muscle: 'triceps',
    muscleId: 7,
  },
  {
    name: 'triceps frances com halter',
    level: 'all',
    muscle: 'triceps',
    muscleId: 7,
  },
  {
    name: 'triceps frances unilateral',
    level: 'all',
    muscle: 'triceps',
    muscleId: 7,
  },
  {
    name: 'triceps polia barra w',
    level: 'all',
    muscle: 'triceps',
    muscleId: 7,
  },
  {
    name: 'triceps banco',
    level: 'all',
    muscle: 'triceps',
    muscleId: 7,
  },
  {
    name: 'Triceps paralelas',
    level: 'all',
    muscle: 'triceps',
    muscleId: 7,
  },
  {
    name: 'triceps frances com halter',
    level: 'all',
    muscle: 'triceps',
    muscleId: 7,
  },
  {
    name: 'triceps frances com corda',
    level: 'all',
    muscle: 'triceps',
    muscleId: 7,
  },
  {
    name: 'triceps polia inverso',
    level: 'all',
    muscle: 'triceps',
    muscleId: 7,
  },
  {
    name: 'Triceps testa com barra reta',
    level: 'all',
    muscle: 'triceps',
    muscleId: 7,
  },
  {
    name: 'triceps frances com barra w',
    level: 'all',
    muscle: 'triceps',
    muscleId: 7,
  },
  {
    name: 'triceps testa com barra w',
    level: 'all',
    muscle: 'triceps',
    muscleId: 7,
  },
  {
    name: 'triceps frances com barra reta',
    level: 'all',
    muscle: 'triceps',
    muscleId: 7,
  },
  {
    name: 'triceps testa com halteres',
    level: 'all',
    muscle: 'triceps',
    muscleId: 7,
  },
  {
    name: 'triceps testa com barra neutra',
    level: 'all',
    muscle: 'triceps',
    muscleId: 7,
  },
  {
    name: 'triceps polia com triangulo',
    level: 'all',
    muscle: 'triceps',
    muscleId: 7,
  },
  {
    name: 'triceps polia inverso unilateral',
    level: 'all',
    muscle: 'triceps',
    muscleId: 7,
  },
  {
    name: 'triceps polia inverso',
    level: 'all',
    muscle: 'triceps',
    muscleId: 7,
  },
  {
    name: 'panturrilha em pé maquina pés retos',
    level: 'all',
    muscle: 'panturrilha',
    muscleId: 9,
  },
  {
    name: 'panturrilha sentado pés retos',
    level: 'all',
    muscle: 'panturrilha',
    muscleId: 9,
  },
  {
    name: 'panturrilhas em pé unilateral',
    level: 'all',
    muscle: 'panturrilha',
    muscleId: 9,
  },
  {
    name: 'Panturrilha em pé maquina pés abduzidos',
    level: 'all',
    muscle: 'panturrilha',
    muscleId: 9,
  },
  {
    name: 'panturrilhas leg press unilateral',
    level: 'all',
    muscle: 'panturrilha',
    muscleId: 9,
  },
  {
    name: 'panturrilhas sentado unilteral',
    level: 'all',
    muscle: 'panturrilha',
    muscleId: 9,
  },
  {
    name: 'panturrilhas leg press pés aduzidos',
    level: 'all',
    muscle: 'panturrilha',
    muscleId: 9,
  },
  {
    name: 'panturrilhas leg press pés abduzidos',
    level: 'all',
    muscle: 'panturrilha',
    muscleId: 9,
  },
  {
    name: 'panturrilha leg press pés retos',
    level: 'all',
    muscle: 'panturrilha',
    muscleId: 9,
  },
  {
    name: 'panturrilha em pé maquina pés aduzidos',
    level: 'all',
    muscle: 'panturrilha',
    muscleId: 9,
  },
  {
    name: 'panturrilha sentado pés aduzidos',
    level: 'all',
    muscle: 'panturrilha',
    muscleId: 9,
  },
  {
    name: 'panturrilha sentado pés abduzidos',
    level: 'all',
    muscle: 'panturrilha',
    muscleId: 9,
  },
];
