//TODO Other Exercises, now its only for chest

export const EXERCISES = [
  {
    name: 'Supino reto com halter',
    level: 'intermediate_beginner',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino inclinado com halter',
    level: 'intermediate_beginner',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino declinado com halter',
    level: 'intermediate_beginner',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino maquina sentado',
    level: 'intermediate_beginner',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino maquina inclinado',
    level: 'beginner',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino maquina reto',
    level: 'beginner',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Peck deck',
    level: 'beginner',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Flexão de braços',
    level: 'beginner',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Cross over para parte inferior',
    level: 'beginner',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Cross over para parte medial',
    level: 'beginner',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino reto com barra',
    level: 'beginner',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Crucifixo reto com halteres',
    level: 'beginner',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Crucifixo fly máquina',
    level: 'beginner',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino reto com barra',
    level: 'ntermediate_beginner',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino inclinado com barra',
    level: 'intermediate_beginner',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino reto com halter',
    level: 'all',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino inclinado com halter',
    level: 'all',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino maquina sentado',
    level: 'all',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino maquina inclinado',
    level: 'intermediary',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino maquina reto',
    level: 'intermediary',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Crucifixo reto com halteres',
    level: 'intermediary',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Crucifixo inclinado com halteres',
    level: 'intermediary',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Crucifixo Reto cabo',
    level: 'intermediary',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Crucifixo inclinado cabo',
    level: 'intermediary',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Fly machine',
    level: 'intermediary',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Cross over para parte inferior',
    level: 'intermediary',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Cross over para parte medial',
    level: 'intermediary',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino reto com barra',
    level: 'advanced',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino inclinado com barra',
    level: 'advanced',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino declinado com barra',
    level: 'advanced',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino reto com barra neutra',
    level: 'advanced',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino inclinado com barra neutra',
    level: 'advanced',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino reto com halter',
    level: 'intermediate_advanced',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino inclinado com halter',
    level: 'intermediate_advanced',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino declinado com halter',
    level: 'intermediate_advanced',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino maquina sentado',
    level: 'intermediate_advanced',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino maquina inclinado',
    level: 'intermediate_advanced',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino maquina reto',
    level: 'intermediate_advanced',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Crucifixo reto com halteres',
    level: 'intermediate_advanced',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Crucifixo inclinado com halteres',
    level: 'intermediate_advanced',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Crucifixo declinado com halteres',
    level: 'all',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Crucifixo Reto cabo',
    level: 'advanced',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Crucifixo inclinado cabo',
    level: 'advanced',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Crucifixo declinado cabo',
    level: 'advanced',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Fly machine',
    level: 'advanced',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Pullover com halter',
    level: 'advanced',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Paralelas',
    level: 'advanced',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Cross over para parte inferior',
    level: 'all',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Cross over para parte medial',
    level: 'intermediate_advanced',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Cross over para parte superior',
    level: 'intermediate_advanced',
    muscle: 'chest',
    muscleId: 1,
  },

  {
    name: 'Supino reto com barra',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino inclinado com barra',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino declinado com barr',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino reto com barra neutra',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },

  {
    name: 'Supino inclinado com barra neutra',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino reto com halter',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino inclinado com halter',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino maquina sentado',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino maquina inclinado',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Supino maquina reto',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Crucifixo reto com halteres',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Crucifixo inclinado com halteres',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },

  {
    name: 'Crucifixo declinado com halteres',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },

  {
    name: 'Crucifixo Reto cabo',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Crucifixo inclinado cabo',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Crucifixo declinado cabo',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Fly machine',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Pullover com halter',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Paralelas',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Cross over para parte inferior',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Cross over para parte medial',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Cross over para parte superior',
    level: 'pro',
    muscle: 'chest',
    muscleId: 1,
  },
  {
    name: 'Pulldown com corda',
    level: 'intermediate_beginner',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulldown barra reta cabo',
    level: 'intermediate_beginner',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada com corda no Cabo',
    level: 'intermediate_beginner',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada baixa Neutra',
    level: 'intermediate_beginner',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada baixa Supinada',
    level: 'intermediate_beginner',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada baixa Pronada',
    level: 'intermediate_beginner',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada Maquina convergente Neutra',
    level: 'beginner',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada Maquina convergente Supinada',
    level: 'beginner',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada Maquina convergente Pronada',
    level: 'beginner',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulley frente fechado',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulley frente supinado',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulldown com corda',
    level: 'intermediary',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulldown barra reta cabo',
    level: 'intermediary',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada com corda no Cabo',
    level: 'intermediary',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada com corda no Cabo',
    level: 'intermediary',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada baixa Neutra',
    level: 'intermediary',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada baixa Supinada',
    level: 'intermediary',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada baixa Pronada',
    level: 'intermediary',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada Maquina convergente Neutra',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada Maquina convergente Supinada',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada Maquina convergente Pronada',
    level: 'intermediary',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulley frente fechado',
    level: 'intermediary',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulley frente supinado',
    level: 'intermediary',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Levantamento terra 1/2 movimento',
    level: 'advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Levantamento terra completo',
    level: 'advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulldown com corda',
    level: 'advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulldown barra reta cabo',
    level: 'advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada banco livre com halteres Supinada',
    level: 'advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada banco livre com halteres Pronada',
    level: 'advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada unilateral com Halteres',
    level: 'advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada baixa Neutra',
    level: 'advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada baixa Supinada',
    level: 'advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada baixa Pronada',
    level: 'advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada Maquina convergente Neutra',
    level: 'advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada Maquina convergente Supinada',
    level: 'advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada Maquina convergente Pronada',
    level: 'advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada Cavalo',
    level: 'advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada curvada Supinada',
    level: 'advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada curvada Pronada',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Puxador convergente Neutro',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Puxador convergente Supinado',
    level: 'advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Puxador convergente Pronado',
    level: 'advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulley Costas Pronado',
    level: 'advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulley Costas Neutro',
    level: 'advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulley Costas fechado',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulley Costas supinado',
    level: 'all',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulley Costas pronado',
    level: 'intermediate_advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Barra fixa neutra',
    level: 'intermediate_advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Barra fixa supinada',
    level: 'intermediate_advanced',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Barra fixa pronada',
    level: 'intermediate_advanced',
    muscle: 'back',
    muscleId: 2,
  },

  {
    name: 'Levantamento terra 1/2 movimento"',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Levantamento terra completo',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulldown com corda',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada banco livre com halteres Supinada',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada banco livre com halteres Pronada',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada unilateral com Halteres',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada baixa Neutra',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada baixa Supinada',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada baixa Pronada',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada Maquina convergente Neutra',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada Maquina convergente Supinada',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada Maquina convergente Pronada',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada Cavalo',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada curvada Supinada',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Remada curvada Pronada',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Puxador convergente Neutro',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Puxador convergente Supinado',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Puxador convergente Pronado',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulley Costas Pronado',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulley Costas Neutro',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulley frente fechado',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulley frente supinado',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Pulley frente pronado',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Barra fixa neutra',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Barra fixa supinada',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
  {
    name: 'Barra fixa pronada',
    level: 'pro',
    muscle: 'back',
    muscleId: 2,
  },
];
